version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /code
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=htracker
      - PGHOST=db
      - PGPASSWORD=htracker_password
      - PGDATABASE=htracker
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./
        target: /code
    command: bash -c "npm install && npm start"
  db:
    image: 'postgres:11.1'
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/setup/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=habittr
      - POSTGRES_USER=htracker
      - POSTGRES_PASSWORD=habittr_password
volumes:
  dbdata: